### ISSUE TITLE
Duplicate searchBar

### ISSUE THREAD

**Issue by AymKh** [MDS-ISALIB/mds-cms#17]
for the desktop view, whenever the search bar is clicked, a second one appears next to it...
That is related to the document. click listener you have under /js/main.js

**Comment by MDS-ISALIB** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [prevent duplicate search from appearing](https://trello.com/c/5WkDdpuc/44-prevent-duplicate-search-from-appearing)
