### ISSUE TITLE
Dev Settings

### ISSUE THREAD

**Issue by AymKh** [MDS-ISALIB/mds-cms#19]
Dev settings should be implemented in order to be able to test the code locally before deploying
(start with dynamically generating links based on hostname [localhost, mdsb.tn])

**Comment by MDS-ISALIB** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dev settings (hostName)](https://trello.com/c/G6hiyLSP/51-dev-settings-hostname)
